version: '3'

services:

  mysql-khala:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: hello
    volumes:
      - ./init-files:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    ports:
      - "3308:3306"

